// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrmvWYkbIVkKv1vArGQbi-co1mqIQUPFA',
    appId: '1:1075022672139:web:e89551e758bbecb3e2b20e',
    messagingSenderId: '1075022672139',
    projectId: 'opsaide-up-001',
    authDomain: 'opsaide-up-001.firebaseapp.com',
    storageBucket: 'opsaide-up-001.appspot.com',
    measurementId: 'G-P16YN1KN0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMB5DpAAZ3eY16tohixjYB219yY3HD98',
    appId: '1:1075022672139:android:b2ccf7798500e4ade2b20e',
    messagingSenderId: '1075022672139',
    projectId: 'opsaide-up-001',
    storageBucket: 'opsaide-up-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAK5S137tsHN6VoeAmT0seYFcqA9-jYg',
    appId: '1:1075022672139:ios:2133775eeac9d7f6e2b20e',
    messagingSenderId: '1075022672139',
    projectId: 'opsaide-up-001',
    storageBucket: 'opsaide-up-001.appspot.com',
    iosBundleId: 'com.example.opsaideLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAK5S137tsHN6VoeAmT0seYFcqA9-jYg',
    appId: '1:1075022672139:ios:2133775eeac9d7f6e2b20e',
    messagingSenderId: '1075022672139',
    projectId: 'opsaide-up-001',
    storageBucket: 'opsaide-up-001.appspot.com',
    iosBundleId: 'com.example.opsaideLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrmvWYkbIVkKv1vArGQbi-co1mqIQUPFA',
    appId: '1:1075022672139:web:ab16ae476de4e559e2b20e',
    messagingSenderId: '1075022672139',
    projectId: 'opsaide-up-001',
    authDomain: 'opsaide-up-001.firebaseapp.com',
    storageBucket: 'opsaide-up-001.appspot.com',
    measurementId: 'G-NF3FE6JMFV',
  );
}
